### ISSUE TITLE
Problem with relative paths in index.yaml files

### ISSUE THREAD

**Issue by shibumi** [openSUSE/helm-mirror#29]
helm-mirror works well if the upstream index.yaml file holds only URLs.
If the index.yaml file holds relative paths ( for example jetstack ) helm-mirror will fail:

```yaml
  - apiVersion: v1
    appVersion: v0.0.1-alpha.1
    created: "2021-01-25T12:19:54.966Z"
    description: A Helm chart for istio-csr
    digest: 630da21d66e68d4da910e771279548b96e848b8fcbfc66e98b5a953a023b1ff2
    home: https://github.com/jetstack/istio-csr
    maintainers:
    - email: joshua.vanleeuwen@jetstack.io
      name: joshvanl
    name: cert-manager-istio-csr
    sources:
    - https://github.com/cert-manager/istio-csr
    type: application
    urls:
    - charts/cert-manager-istio-csr-v0.0.1-alpha.1.tgz
```

Error Message: Get charts/cert-manager-v0.15-alpha.3.tgz: unsupported protocol scheme ""
