### ISSUE TITLE
inspect images: add skopeo sync compatible output

### ISSUE THREAD

**Issue by flavio** [openSUSE/helm-mirror#4]
Add a new output format for the inspect images command. This should print a yaml file compatible with what [skopeo sync](https://github.com/containers/skopeo/blob/5b89bc0da6544c1b55dbe0a2e4a30b904aa15bc9/docs/skopeo.1.md#skopeo-sync-1) expects.

For example, it should provide something like that:

```yaml
registry.suse.com:
  images:
     nginx-ingress-controller:
        - 0.15.0
     foobar:
        - tag1
        - tag2
        - tag3
```

Assuming that `registry.suse.com/nginx-ingress-controller:0.15.0`, `registry.suse.com/foobar:tag1`, `registry.suse.com/foobar:tag2` and `registry.suse.com/foobar:tag3` are mentioned inside of the helm charts.
